version: "3.9"

services:
  app:
    build: .
    container_name: fraud_chatbot_app
    ports:
      - "8501:8501"
    environment:
      # DB
      DB_URL: ${DB_URL}

      # Pinecone
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX: ${PINECONE_INDEX}

      # Gemini
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL}

      # Ollama
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_EMBED_MODEL: qwen3-embedding:0.6b

    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:0.12.3
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_HOST: 0.0.0.0
      OLLAMA_ORIGINS: "*"
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve &
      sleep 5 &&
      ollama pull qwen3-embedding:0.6b &&
      wait"

volumes:
  ollama_data:
